const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94774971556"
const SESSION_ID = "PRABATH-MD~9dZ3TD6Z#hyD1WdHbNxjKKDST__p0-ZQzy4tFNC8O4g8ACnYObfk"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
